export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="h-20 bg-black text-white flex items-center justify-center relative">
          DASHBOARD PAGE
        </nav>
        {children}
      </body>
    </html>
  );
}
